### ISSUE TITLE
TextureManager再修正

### ISSUE THREAD

**Issue by yuki-nakano** [ono-hikaru81/SuperiorButlers#24]
- ~アニメーションの追加~
- 戻り値の変更

**Comment by Takuto-Miyoshi** [comment]
アニメーションはそれ用に管理クラス作った方がいいと思いますー。
どんな形で使うかわからないけど、１度呼び出したら管理クラス側で自動で処理してくれるのが理想なので。
そうなると別ブランチ切って…ｱｱｱｱｱｱｱ。。。

**Comment by yuki-nakano** [comment]
了解それでやってみる。
ブランチ分けた方がいいんか…
